name: CI-compile

on:
  push:
  pull_request:

jobs:
  build:
    name: PS2Ident compilation
    runs-on: ubuntu-latest
    container: ghcr.io/ps2homebrew/ps2homebrew:main
    strategy:
      fail-fast: false
      matrix:
        debug: [DEBUG=0 DSNET_HOST_SUPPORT=0, DEBUG=1 DSNET_HOST_SUPPORT=1, DEBUG=1 COH=1]
    steps:
    - uses: actions/checkout@v4

    - name: Compile project
      run: |
        make ${{ matrix.debug }}
    # commands for compiling your project

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: PS2Ident-${{ matrix.debug }}-${{ github.sha }}
        path: |
          PS2Ident.elf
          README.md
          changelog.txt

  release:
    needs: [build]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/new'
    steps:
    - uses: actions/checkout@v4

    - name: Download PS2Ident artifact
      uses: actions/download-artifact@v4
      with:
        name: "PS2Ident-DEBUG=0 DSNET_HOST_SUPPORT=0-${{ github.sha }}"
        path: PS2Ident

    - name: Prepare PS2Ident archive
      run: |
        7z a PS2Ident.7z PS2Ident/*

    - name: Download PS2Ident for PS2TOOL artifact
      uses: actions/download-artifact@v4
      with:
        name: "PS2Ident-DEBUG=0 DSNET_HOST_SUPPORT=0-${{ github.sha }}"
        path: PS2Ident-PS2TOOL

    - name: Prepare PS2Ident for PS2TOOL archive
      run: |
        7z a PS2Ident-debug.7z PS2Ident-PS2TOOL/*

    - name: Download PS2Ident for SYSTEM2x6 artifact
      uses: actions/download-artifact@v4
      with:
        name: "PS2Ident-DEBUG=1 COH=1-${{ github.sha }}"
        path: PS2Ident-SYSTEM2x6

    - name: Prepare PS2Ident for ARCADE archive
      run: |
        7z a PS2Ident-system2x6_arcade.7z PS2Ident-SYSTEM2x6/*

    - name: Create pre-release
      if: github.ref == 'refs/heads/new'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        automatic_release_tag: "latest"
        title: "Development build"
        files: |
          PS2Ident.7z
          PS2Ident-debug.7z
          PS2Ident-system2x6_arcade.7z

    - name: Create Tagged Release Draft
      if: startsWith(github.ref, 'refs/tags/v')
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: "stable"
        draft: true
        files: |
          PS2Ident.7z
          PS2Ident-debug.7z
          PS2Ident-system2x6_arcade.7z

